name: Deploy to Fly

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Application
        run: yarn build

      - name: Install Flyctl
        uses: superfly/flyctl-actions@master
        with:
          version: 'latest'

      - name: Deploy
        run: flyctl deploy --config ./fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
